#!/usr/bin/env tsx
/**
 * Generate `src/generated/build-meta.ts` at prebuild time.
 *
 * Pre-PR #345 the tool count was a hand-maintained "29 tools" / "33 tools"
 * literal sprinkled across README + help-content-en/es. Same with the
 * package version stamped into the User-Agent. Both drifted silently
 * (M3 + M9 in the MCP audit). The fix is to derive both at build time.
 *
 *   - `TOOL_COUNT` — counts `defineTool({` occurrences across
 *     `src/tools/*.ts` (excluding tests).
 *   - `VERSION` — package.json `.version` literal.
 *
 * Consumers:
 *   - `src/lib/api-client.ts` stamps `VERSION` into User-Agent.
 *   - `src/tools/help-content-*.ts` use `TOOL_COUNT` so README / help
 *     text never drift from reality.
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const toolsDir = join(pkgRoot, "src", "tools");
const outDir = join(pkgRoot, "src", "generated");
const outFile = join(outDir, "build-meta.ts");

const DEFINE_TOOL_REGEX = /defineTool\(\{/g;

function countTools(): number {
  let total = 0;
  for (const entry of readdirSync(toolsDir, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith(".ts")) continue;
    if (entry.name.endsWith(".test.ts")) continue;
    const text = readFileSync(join(toolsDir, entry.name), "utf8");
    const matches = text.match(DEFINE_TOOL_REGEX);
    if (matches) total += matches.length;
  }
  return total;
}

function readVersion(): string {
  const pkgPath = join(pkgRoot, "package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { version: string };
  return pkg.version;
}

function main(): void {
  const TOOL_COUNT = countTools();
  const VERSION = readVersion();

  mkdirSync(outDir, { recursive: true });

  const banner = "// AUTOGENERATED by scripts/gen-build-meta.ts — do not edit.\n";
  const body = [
    banner,
    `export const TOOL_COUNT = ${TOOL_COUNT};`,
    `export const VERSION = ${JSON.stringify(VERSION)};`,
    "",
  ].join("\n");
  writeFileSync(outFile, body);

  process.stdout.write(`gen-build-meta: TOOL_COUNT=${TOOL_COUNT} VERSION=${VERSION}\n`);
}

main();
